version: '3'

services:
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: banco
      MYSQL_USER: root  
    ports:
      - "3306:3306"
    networks:
    - stack-yourcontrol

  webserver:
    image: php:7.2-apache
    container_name: webserver
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "80:80"
    networks:
      - stack-yourcontrol
    links:
      - db
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - stack-yourcontrol
    links:
      - db

networks: 
  stack-yourcontrol:
